#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_demultiplex_serial
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
# NB qiime1
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_temp

# splitting libraries
echo "splitting libraries"
time split_libraries_fastq.py --barcode_type 12 -i SeqPrep_joined/seqprep_assembled.fastq.gz -m map_incomplete.tsv -b SeqPrep_joined/seqprep_assembled.fastq_barcodes.fastq  --rev_comp_barcode --rev_comp_mapping_barcodes  -o slout -q 19

# counting sequences
echo "counting sequences"
time count_seqs.py -i slout/seqs.fna

source deactivate qiime1


