#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_joining
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
# NB qiime1
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_temp

# joining Illumina sequences
echo "join paried ends"
time join_paired_ends.py -m SeqPrep -b Index.fastq.gz -f Read1.fastq.gz -r Read2.fastq.gz -o SeqPrep_joined

source deactivate qiime1


