#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N compare_categoriesvegetation
#PBS -A d411-training

cd $PBS_O_WORKDIR

# setting temporary directory
export TMPDIR=~/qiime_temp

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"

# NB qiime1
source activate qiime1

module load R-3.3.1-gcc-6.2.0-zjrjm3s

# loading compare categories
echo "loading compare categories"
time compare_categories.py --method anosim  -i cdout/bdiv_even623/weighted_unifrac_dm.txt -m map2018.tsv -c SampleVegetation -o anosim_out -n 99

source deactivate qiime1


