#!/bin/bash --login
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=2
#PBS -N core_diversity2018(P)
#PBS -A d411-training

cd $PBS_O_WORKDIR

# setting temporary directory
export TMPDIR=~/qiime_temp

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"

# NB qiime1
source activate qiime1

# loading core_diversity_analysis
echo "loading core_diversity_analysis"
time core_diversity_analyses.py --recover_from_failure -o cdout -i otus/otu_table.biom -m map2018.tsv -t SILVA_128_QIIME_release/trees/97/97_otus.tre -e 33878

source deactivate qiime1


