#!/bin/bash --login
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=2
#PBS -N heatmap2018_new6
#PBS -A d411-training

cd $PBS_O_WORKDIR

# setting temporary directory
export TMPDIR=~/qiime_temp

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"

# NB qiime1
source activate qiime1

# loading make otu heatmap
echo "loading make otu heatmap"
time make_otu_heatmap.py -o heatmap6.pdf -i cdout/taxa_plots/table_mc33878_sorted_L2.biom --color_scheme Blues -m map2018.tsv

source deactivate qiime1

