#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_PICKINGOTU_parallel
#PBS -A d411-training

cd $PBS_O_WORKDIR

# setting temporary directory
export TMPDIR=~/qiime_temp

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"

# NB qiime1
source activate qiime1

# picking OTUs
echo "Picking OTUs with closed reference"
time pick_closed_reference_otus.py -i slout/seqs.fna -o otus -a -O 16

source deactivate qiime1


