#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N summarize_taxa
#PBS -A d411-training

cd $PBS_O_WORKDIR

# setting temporary directory
export TMPDIR=~/qiime_temp

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"

# NB qiime1
source activate qiime1

# loading summarize_taxa
echo "loading summarize taxa"
time summarize_taxa.py -i otus/otu_table.biom -m map2018.tsv -L 2,3 -o ./tax

source deactivate qiime1

